import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  ru: {
    // Navigation
    home: 'Главная',
    movies: 'Фильмы',
    series: 'Сериалы',
    actors: 'Актеры',
    profile: 'Профиль',
    signIn: 'Войти',
    signUp: 'Регистрация',
    signInShort: 'Вход',
    signUpShort: 'Регистр',
    signOut: 'Выйти',
    search: 'Поиск',
    searchPlaceholder: 'Поиск фильмов, сериалов...',
    
    // Auth
    welcome: 'Добро пожаловать',
    signInTitle: 'Войдите в свой аккаунт',
    signUpTitle: 'Создайте новый аккаунт',
    email: 'Email',
    password: 'Пароль',
    confirmPassword: 'Подтвердите пароль',
    forgotPassword: 'Забыли пароль?',
    resetPassword: 'Сброс пароля',
    backToSignIn: 'Вернуться к входу',
    createAccount: 'Зарегистрироваться',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    
    // Home
    heroTitle: 'Откройте мир',
    heroSubtitle: 'кино и сериалов',
    heroDescription: 'Исследуйте огромную коллекцию фильмов и сериалов.',
    heroDescriptionAuth: 'Войдите, чтобы сохранять избранное, оставлять комментарии и ставить оценки.',
    watchMovies: 'Смотреть фильмы',
    watchSeries: 'Смотреть сериалы',
    popularMovies: 'Популярные фильмы',
    ongoingSeries: 'Идущие сериалы',
    allMovies: 'Все фильмы',
    allSeries: 'Все сериалы',
    quickNavigation: 'Быстрая навигация',
    moviesDesc: 'Исследуйте огромную коллекцию фильмов различных жанров. Читайте описания, смотрите трейлеры и оценивайте понравившиеся.',
    seriesDesc: 'Найдите интересные сериалы, следите за идущими сезонами и открывайте новые захватывающие истории.',
    goTo: 'Перейти',
    
    // Movies/Series
    catalog: 'Каталог',
    filters: 'Фильтры',
    sortBy: 'Сортировка',
    sortDefault: 'По умолчанию',
    sortYear: 'По году',
    sortRating: 'По рейтингу',
    sortTitle: 'По названию',
    sortByDate: 'По дате рождения',
    sortNameAsc: 'Имя (А–Я)',
    sortNameDesc: 'Имя (Я–А)',
    sortDateAsc: 'Дата рождения (старые)',
    sortDateDesc: 'Дата рождения (новые)',
    more: 'еще',
    gridView: 'Сетка',
    listView: 'Список',
    loadMore: 'Загрузить еще',
    loading: 'Загрузка...',
    notFound: 'Не найдено',
    tryDifferentSearch: 'Попробуйте изменить параметры поиска',
    genre: 'Жанр',
    yearFrom: 'Год от',
    yearTo: 'Год до',
    actor: 'Актёр',
    ongoing: 'Идёт',
    back: 'Назад',
    
    // Details
    rating: 'Оценить',
    changeRating: 'Изменить оценку',
    loginToRate: 'Войдите, чтобы оценить',
    comments: 'Комментарии',
    addComment: 'Добавить комментарий',
    cancel: 'Отмена',
    send: 'Отправить',
    noComments: 'Пока нет комментариев',
    loginToComment: 'Войти для комментирования',
    enterComment: 'Введите ваш комментарий...',
    trailer: 'Трейлер',
    addToFavorites: 'Добавить в избранное',
    removeFromFavorites: 'Удалить из избранного',
    similarMovies: 'Похожие фильмы',
    similarSeries: 'Похожие сериалы',
    seasons: 'Сезонов',
    episodes: 'Эпизодов',
    
    // Profile
    favorites: 'Избранное',
    myComments: 'Мои комментарии',
    myRatings: 'Мои рейтинги',
    edit: 'Редактировать',
    delete: 'Удалить',
    save: 'Сохранить',
    close: 'Закрыть',
    noFavorites: 'Нет избранных фильмов',
    noRatings: 'Нет рейтингов',
    
    // Actors
    actorsCatalog: 'Каталог всех актеров',
    searchActors: 'Поиск актеров...',
    actorMovies: 'Фильмы',
    actorSeries: 'Сериалы',
    moviesCount: 'Фильмов',
    seriesCount: 'Сериалов',
    noActorMovies: 'Нет фильмов с участием этого актера',
    noActorSeries: 'Нет сериалов с участием этого актера',
    selectActor: 'Выберите актера, чтобы увидеть подробности',
    tipExploreActor: 'Совет: откройте проект актера, чтобы увидеть больше информации.',
    errorLoadingActorDetails: 'Ошибка при загрузке информации об актере',
    
    // Common
    year: 'Год',
    genres: 'Жанры',
    description: 'Описание',
    firstName: 'Имя',
    lastName: 'Фамилия',
    username: 'Имя пользователя',
    noAccount: 'Нет аккаунта?',
    checkEmail: 'Проверьте почту',
    emailSent: 'Мы отправили инструкции по сбросу пароля на ваш email',
    total: 'Всего',
    remove: 'Удалить',
    otpCode: 'Код OTP (6 цифр)',
    newPassword: 'Новый пароль',
    enterOtpAndPassword: 'Введите код OTP и новый пароль',
    yourRating: 'Ваша оценка',
    averageRating: 'Средняя оценка',
    changed: 'изменен',
    movie: 'Фильм',
    personalCabinet: 'Личный кабинет',
    manageProfile: 'Управление вашим профилем',
    ratingSaved: 'Оценка сохранена',
    commentAdded: 'Комментарий добавлен',
    commentUpdated: 'Комментарий обновлен',
    commentDeleted: 'Комментарий удален',
    ratingError: 'Ошибка при сохранении оценки',
    commentError: 'Ошибка при добавлении комментария',
    ratingRangeError: 'Оценка должна быть от 1 до 5',
    enterCommentText: 'Введите текст комментария',
    movieNotFound: 'Фильм не найден',
    seriesNotFound: 'Сериал не найден',
    actorNotFound: 'Актер не найден',
    resetFilters: 'Сбросить фильтры',
    passwordsDoNotMatch: 'Пароли не совпадают',
    signingIn: 'Вход...',
    signingUp: 'Регистрация...',
    errorLoadingMovies: 'Ошибка загрузки фильмов',
    errorLoadingSeries: 'Ошибка загрузки сериалов',
    errorLoadingActors: 'Ошибка загрузки актеров',
    errorLoadingFavorites: 'Ошибка загрузки избранного',
    errorLoadingComments: 'Ошибка загрузки комментариев',
    errorLoadingRatings: 'Ошибка загрузки рейтингов',
    errorToggleFavorite: 'Ошибка при изменении избранного',
    trustedUser: 'Доверенный пользователь',
    becomeTrustedUser: 'Стать доверенным пользователем',
    trustedUserBenefits: 'Получите расширенные возможности: возможность ставить оценки фильмам и сериалам',
    trustedUserDescription: 'Вы являетесь доверенным пользователем! Теперь вы можете ставить оценки фильмам и сериалам.',
    sendOtp: 'Отправить OTP',
    verifyOtp: 'Подтвердить OTP',
    otpSent: 'OTP код отправлен на ваш email',
    otpSentToEmail: 'OTP код отправлен на ваш email',
    trustedUserUpgraded: 'Поздравляем! Вы стали доверенным пользователем',
    enterEmail: 'Введите email',
    enterValidOtp: 'Введите корректный OTP код (6 цифр)',
    errorSendingOtp: 'Ошибка при отправке OTP',
    errorVerifyingOtp: 'Ошибка при подтверждении OTP',
    errorGettingUserId: 'Ошибка получения ID пользователя',
    sending: 'Отправка',
    verifying: 'Подтверждение',
    searchResults: 'Найдено',
  },
  en: {
    // Navigation
    home: 'Home',
    movies: 'Movies',
    series: 'Series',
    actors: 'Actors',
    profile: 'Profile',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signInShort: 'Login',
    signUpShort: 'Join',
    signOut: 'Sign Out',
    search: 'Search',
    searchPlaceholder: 'Search movies, series...',
    
    // Auth
    welcome: 'Welcome',
    signInTitle: 'Sign in to your account',
    signUpTitle: 'Create a new account',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot password?',
    resetPassword: 'Reset Password',
    backToSignIn: 'Back to Sign In',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    
    // Home
    heroTitle: 'Discover the world of',
    heroSubtitle: 'movies and series',
    heroDescription: 'Explore a huge collection of movies and series.',
    heroDescriptionAuth: 'Sign in to save favorites, leave comments and rate.',
    watchMovies: 'Watch Movies',
    watchSeries: 'Watch Series',
    popularMovies: 'Popular Movies',
    ongoingSeries: 'Ongoing Series',
    allMovies: 'All Movies',
    allSeries: 'All Series',
    quickNavigation: 'Quick Navigation',
    moviesDesc: 'Explore a huge collection of movies of various genres. Read descriptions, watch trailers and rate your favorites.',
    seriesDesc: 'Find interesting series, follow ongoing seasons and discover new exciting stories.',
    goTo: 'Go to',
    
    // Movies/Series
    catalog: 'Catalog',
    filters: 'Filters',
    sortBy: 'Sort By',
    sortDefault: 'Default',
    sortYear: 'By Year',
    sortRating: 'By Rating',
    sortTitle: 'By Name',
    sortByDate: 'By Date of Birth',
    sortNameAsc: 'Name (A–Z)',
    sortNameDesc: 'Name (Z–A)',
    sortDateAsc: 'Birthdate (Oldest)',
    sortDateDesc: 'Birthdate (Newest)',
    more: 'more',
    gridView: 'Grid',
    listView: 'List',
    loadMore: 'Load More',
    loading: 'Loading...',
    notFound: 'Not Found',
    tryDifferentSearch: 'Try different search parameters',
    genre: 'Genre',
    yearFrom: 'Year From',
    yearTo: 'Year To',
    actor: 'Actor',
    ongoing: 'Ongoing',
    back: 'Back',
    
    // Details
    rating: 'Rate',
    changeRating: 'Change Rating',
    loginToRate: 'Sign in to rate',
    comments: 'Comments',
    addComment: 'Add Comment',
    cancel: 'Cancel',
    send: 'Send',
    noComments: 'No comments yet',
    loginToComment: 'Sign in to comment',
    enterComment: 'Enter your comment...',
    trailer: 'Trailer',
    addToFavorites: 'Add to Favorites',
    removeFromFavorites: 'Remove from Favorites',
    similarMovies: 'Similar Movies',
    similarSeries: 'Similar Series',
    seasons: 'Seasons',
    episodes: 'Episodes',
    
    // Profile
    favorites: 'Favorites',
    myComments: 'My Comments',
    myRatings: 'My Ratings',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    close: 'Close',
    noFavorites: 'No favorite movies',
    noRatings: 'No ratings',
    
    // Actors
    actorsCatalog: 'Catalog of all actors',
    searchActors: 'Search actors...',
    actorMovies: 'Movies',
    actorSeries: 'Series',
    moviesCount: 'Movies',
    seriesCount: 'Series',
    noActorMovies: 'No movies with this actor',
    noActorSeries: 'No series with this actor',
    selectActor: 'Select an actor to see details',
    tipExploreActor: 'Tip: open any of the actor’s projects to discover more details.',
    errorLoadingActorDetails: 'Failed to load actor details',
    
    // Common
    year: 'Year',
    genres: 'Genres',
    description: 'Description',
    firstName: 'First Name',
    lastName: 'Last Name',
    username: 'Username',
    noAccount: 'No account?',
    checkEmail: 'Check your email',
    emailSent: 'We sent password reset instructions to your email',
    total: 'Total',
    remove: 'Remove',
    otpCode: 'OTP Code (6 digits)',
    newPassword: 'New Password',
    enterOtpAndPassword: 'Enter OTP and new password',
    yourRating: 'Your Rating',
    averageRating: 'Average Rating',
    changed: 'changed',
    movie: 'Movie',
    personalCabinet: 'Personal Cabinet',
    manageProfile: 'Manage your profile',
    ratingSaved: 'Rating saved',
    commentAdded: 'Comment added',
    commentUpdated: 'Comment updated',
    commentDeleted: 'Comment deleted',
    ratingError: 'Error saving rating',
    commentError: 'Error adding comment',
    ratingRangeError: 'Rating must be between 1 and 5',
    enterCommentText: 'Enter comment text',
    movieNotFound: 'Movie not found',
    seriesNotFound: 'Series not found',
    actorNotFound: 'Actor not found',
    resetFilters: 'Reset Filters',
    passwordsDoNotMatch: 'Passwords do not match',
    signingIn: 'Signing in...',
    signingUp: 'Signing up...',
    errorLoadingMovies: 'Error loading movies',
    errorLoadingSeries: 'Error loading series',
    errorLoadingActors: 'Error loading actors',
    errorLoadingFavorites: 'Error loading favorites',
    errorLoadingComments: 'Error loading comments',
    errorLoadingRatings: 'Error loading ratings',
    errorToggleFavorite: 'Error toggling favorite',
    trustedUser: 'Trusted User',
    becomeTrustedUser: 'Become a Trusted User',
    trustedUserBenefits: 'Get extended features: ability to rate movies and series',
    trustedUserDescription: 'You are a trusted user! Now you can rate movies and series.',
    sendOtp: 'Send OTP',
    verifyOtp: 'Verify OTP',
    otpSent: 'OTP code sent to your email',
    otpSentToEmail: 'OTP code sent to your email',
    trustedUserUpgraded: 'Congratulations! You are now a trusted user',
    enterEmail: 'Enter email',
    enterValidOtp: 'Enter valid OTP code (6 digits)',
    errorSendingOtp: 'Error sending OTP',
    errorVerifyingOtp: 'Error verifying OTP',
    errorGettingUserId: 'Error getting user ID',
    sending: 'Sending',
    verifying: 'Verifying',
    searchResults: 'Found',
  },
  az: {
    // Navigation
    home: 'Ana Səhifə',
    movies: 'Filmlər',
    series: 'Seriallar',
    actors: 'Aktyorlar',
    profile: 'Profil',
    signIn: 'Daxil ol',
    signUp: 'Qeydiyyat',
    signInShort: 'Giriş',
    signUpShort: 'Qeydiyyat',
    signOut: 'Çıxış',
    search: 'Axtarış',
    searchPlaceholder: 'Filmlər, seriallar axtar...',
    
    // Auth
    welcome: 'Xoş gəlmisiniz',
    signInTitle: 'Hesabınıza daxil olun',
    signUpTitle: 'Yeni hesab yaradın',
    email: 'Email',
    password: 'Şifrə',
    confirmPassword: 'Şifrəni təsdiqlə',
    forgotPassword: 'Şifrəni unutmusunuz?',
    resetPassword: 'Şifrəni sıfırla',
    backToSignIn: 'Girişə qayıt',
    createAccount: 'Hesab yarat',
    alreadyHaveAccount: 'Artıq hesabınız var?',
    
    // Home
    heroTitle: 'Kəşf edin',
    heroSubtitle: 'filmlər və seriallar dünyası',
    heroDescription: 'Filmlər və serialların böyük kolleksiyasını kəşf edin.',
    heroDescriptionAuth: 'Sevimliləri saxlamaq, şərh yazmaq və qiymətləndirmək üçün daxil olun.',
    watchMovies: 'Filmlərə bax',
    watchSeries: 'Seriallara bax',
    popularMovies: 'Populyar filmlər',
    ongoingSeries: 'Davam edən seriallar',
    allMovies: 'Bütün filmlər',
    allSeries: 'Bütün seriallar',
    quickNavigation: 'Sürətli naviqasiya',
    moviesDesc: 'Müxtəlif janrlarda filmlərin böyük kolleksiyasını kəşf edin. Təsvirləri oxuyun, treylerlərə baxın və sevimlilərinizi qiymətləndirin.',
    seriesDesc: 'Maraqlı seriallar tapın, davam edən mövsümləri izləyin və yeni maraqlı hekayələr kəşf edin.',
    goTo: 'Keç',
    
    // Movies/Series
    catalog: 'Kataloq',
    filters: 'Filtrlər',
    sortBy: 'Sıralama',
    sortDefault: 'Varsayılan',
    sortYear: 'İlə görə',
    sortRating: 'Reytinqə görə',
    sortTitle: 'Ada görə',
    sortByDate: 'Doğum tarixinə görə',
    sortNameAsc: 'Ad (A-Z)',
    sortNameDesc: 'Ad (Z-A)',
    sortDateAsc: 'Doğum tarixi (köhnə)',
    sortDateDesc: 'Doğum tarixi (yeni)',
    more: 'daha',
    gridView: 'Şəbəkə',
    listView: 'Siyahı',
    loadMore: 'Daha çox yüklə',
    loading: 'Yüklənir...',
    notFound: 'Tapılmadı',
    tryDifferentSearch: 'Fərqli axtarış parametrləri sınayın',
    genre: 'Janr',
    yearFrom: 'İldən',
    yearTo: 'İlə',
    actor: 'Aktyor',
    ongoing: 'Davam edir',
    back: 'Geri',
    
    // Details
    rating: 'Qiymətləndir',
    changeRating: 'Qiyməti dəyiş',
    loginToRate: 'Qiymətləndirmək üçün daxil olun',
    comments: 'Şərhlər',
    addComment: 'Şərh əlavə et',
    cancel: 'Ləğv et',
    send: 'Göndər',
    noComments: 'Hələ şərh yoxdur',
    loginToComment: 'Şərh yazmaq üçün daxil olun',
    enterComment: 'Şərhinizi daxil edin...',
    trailer: 'Treyler',
    addToFavorites: 'Sevimlilərə əlavə et',
    removeFromFavorites: 'Sevimlilərdən sil',
    similarMovies: 'Oxşar filmlər',
    similarSeries: 'Oxşar seriallar',
    seasons: 'Mövsüm',
    episodes: 'Seriya',
    
    // Profile
    favorites: 'Sevimlilər',
    myComments: 'Şərhlərim',
    myRatings: 'Reytinqlərim',
    edit: 'Redaktə et',
    delete: 'Sil',
    save: 'Saxla',
    close: 'Bağla',
    noFavorites: 'Sevimli film yoxdur',
    noRatings: 'Reytinq yoxdur',
    
    // Actors
    actorsCatalog: 'Bütün aktyorların kataloqu',
    searchActors: 'Aktyorlar axtar...',
    actorMovies: 'Filmlər',
    actorSeries: 'Seriallar',
    moviesCount: 'Film',
    seriesCount: 'Serial',
    noActorMovies: 'Bu aktyorun iştirak etdiyi film yoxdur',
    noActorSeries: 'Bu aktyorun iştirak etdiyi serial yoxdur',
    selectActor: 'Məlumat üçün aktyoru seçin',
    tipExploreActor: 'İpucu: daha çox məlumat üçün aktyorun layihələrindən birini açın.',
    errorLoadingActorDetails: 'Aktyor məlumatlarını yükləmək alınmadı',
    
    // Common
    year: 'İl',
    genres: 'Janrlar',
    description: 'Təsvir',
    firstName: 'Ad',
    lastName: 'Soyad',
    username: 'İstifadəçi adı',
    noAccount: 'Hesab yoxdur?',
    checkEmail: 'Emaili yoxlayın',
    emailSent: 'Şifrə sıfırlama təlimatlarını emailinizə göndərdik',
    total: 'Cəmi',
    remove: 'Silin',
    otpCode: 'OTP kodu (6 rəqəm)',
    newPassword: 'Yeni şifrə',
    enterOtpAndPassword: 'OTP kodunu və yeni şifrəni daxil edin',
    yourRating: 'Sizin qiymətiniz',
    averageRating: 'Orta qiymət',
    changed: 'dəyişdirildi',
    movie: 'Film',
    personalCabinet: 'Şəxsi Kabinet',
    manageProfile: 'Profilinizi idarə edin',
    ratingSaved: 'Reytinq saxlanıldı',
    commentAdded: 'Şərh əlavə edildi',
    commentUpdated: 'Şərh yeniləndi',
    commentDeleted: 'Şərh silindi',
    ratingError: 'Reytinqi saxlayarkən xəta',
    commentError: 'Şərh əlavə edərkən xəta',
    ratingRangeError: 'Reytinq 1-dən 5-ə qədər olmalıdır',
    enterCommentText: 'Şərh mətni daxil edin',
    movieNotFound: 'Film tapılmadı',
    seriesNotFound: 'Serial tapılmadı',
    actorNotFound: 'Aktyor tapılmadı',
    resetFilters: 'Filtrləri sıfırla',
    passwordsDoNotMatch: 'Şifrələr uyğun gəlmir',
    signingIn: 'Daxil olunur...',
    signingUp: 'Qeydiyyatdan keçirilir...',
    errorLoadingMovies: 'Filmləri yükləyərkən xəta',
    errorLoadingSeries: 'Serialları yükləyərkən xəta',
    errorLoadingActors: 'Aktyorları yükləyərkən xəta',
    errorLoadingFavorites: 'Sevimliləri yükləyərkən xəta',
    errorLoadingComments: 'Şərhləri yükləyərkən xəta',
    errorLoadingRatings: 'Reytinqləri yükləyərkən xəta',
    errorToggleFavorite: 'Sevimliləri dəyişdirərkən xəta',
    trustedUser: 'Etibarlı İstifadəçi',
    becomeTrustedUser: 'Etibarlı İstifadəçi olun',
    trustedUserBenefits: 'Genişləndirilmiş imkanlar əldə edin: filmlərə və seriallara reytinq vermə imkanı',
    trustedUserDescription: 'Siz etibarlı istifadəçisiniz! İndi filmlərə və seriallara reytinq verə bilərsiniz.',
    sendOtp: 'OTP göndər',
    verifyOtp: 'OTP təsdiqlə',
    otpSent: 'OTP kodu emailinizə göndərildi',
    otpSentToEmail: 'OTP kodu emailinizə göndərildi',
    trustedUserUpgraded: 'Təbriklər! İndi siz etibarlı istifadəçisiniz',
    enterEmail: 'Email daxil edin',
    enterValidOtp: 'Düzgün OTP kodu daxil edin (6 rəqəm)',
    errorSendingOtp: 'OTP göndərilərkən xəta',
    errorVerifyingOtp: 'OTP təsdiqlənərkən xəta',
    errorGettingUserId: 'İstifadəçi ID alınarkən xəta',
    sending: 'Göndərilir',
    verifying: 'Təsdiqlənir',
    searchResults: 'Tapılıb',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'ru';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

